// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjwdlsjatqafzofgdyob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlqd2Rsc2phdHFhZnpvZmdkeW9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzNzM3NzEsImV4cCI6MjA4NTk0OTc3MX0.qb7oiEOwFYiaJRAyM2Ekg_pEgDHcFl8E0VELVW02tvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
